version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/kotlin-spring-practice:cached
      - gradle-cache:/home/vscode/.gradle
    command: sleep infinity
    ports:
      - "8080:8080"
    environment:
      - JAVA_HOME=/usr/local/openjdk-21
    depends_on:
      - postgres
    networks:
      - dev-network

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: kotlin_spring_practice
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dev-network

volumes:
  gradle-cache:
  postgres-data:

networks:
  dev-network:
    driver: bridge
